/**
 * Smile Concepts - Image Asset Map
 * All images are stored locally under /public/assets/<section>/
 * Use these paths directly in Next.js <Image> components or CSS.
 */

export const images = {
  hero: {
    homeTop2024:        "/assets/hero/home-top-2024.jpg",
    homeTop2020:        "/assets/hero/home-top-2020.jpg",
    homeTop2019:        "/assets/hero/home-top-2019.jpg",
    wisdomTeethHero:    "/assets/hero/wisdom-teeth-hero.jpg",
    background:         "/assets/hero/background.jpg",
    homepageBa:         "/assets/hero/homepage-ba.jpg",
    home1:              "/assets/hero/home-1.jpg",
    p2:                 "/assets/hero/p2.jpg",
    aboutUsSand:        "/assets/hero/about-us-sand.jpg",
    orangeSmile:        "/assets/hero/orange-smile-concept.jpg",
  },

  allon4: {
    topGold:     "/assets/allon4/all-on-four-top-gold.jpg",
    allOn4:      "/assets/allon4/all-on-4-904x1024.jpg",
    sunset:      "/assets/allon4/sunset-all-on-4.jpg",
    elderCouple: "/assets/allon4/elder-couple-cooking-dental-implant.jpg",
    allOn6:      "/assets/allon4/All-on-6-1.2.jpg",
    bridge:      "/assets/allon4/Bridge-1-402x1024.jpg",
    stars5:      "/assets/allon4/5-stars.png",
  },

  gallery: {
    sc2:               "/assets/before-after/sc2.jpg",
    sc3:               "/assets/before-after/sc3.jpg",
    sc4:               "/assets/before-after/sc4.jpg",
    sc5:               "/assets/before-after/sc5.jpg",
    gallery1:          "/assets/before-after/gallery-1.jpg",
    gallery2:          "/assets/before-after/gallery-2.jpg",
    kylieVeneers:      "/assets/before-after/kylie-veneers.jpg",
    veneersVsInvisalign: "/assets/before-after/veneers-vs-invisalign.jpg",
    porcelainVeneers:  "/assets/before-after/porcelain-veneers.jpg",
    veneersCost:       "/assets/before-after/veneers-cost.jpg",
    coupleSmiling:     "/assets/visual-story/couple-smiling.jpg",
    beforeAfter4:      "/assets/before-after/before-after-4.jpg",
  },

  services: {
    invisalign:          "/assets/services/invisalign.jpg",
    invisalignBraces:    "/assets/services/invisalign-braces.jpg",
    clearBraces:         "/assets/services/clear-braces.jpg",
    clearBraces2:        "/assets/services/clear-braces-2.jpg",
    porcelainVeneers:    "/assets/services/porcelain-veneers.jpg",
    porcelainVeneers2:   "/assets/services/porcelain-veneers-2.jpg",
    dentalVeneers:       "/assets/services/dental-veneers.jpg",
    sleepDentistry:      "/assets/services/sleep-dentistry.jpg",
    sleepDentistry2:     "/assets/services/sleep-dentistry-2.jpg",
    sleepDentistry3:     "/assets/services/sleep-dentistry-3.jpg",
    sleepApnea:          "/assets/services/sleep-apnea.jpg",
    sleepApnoea:         "/assets/services/sleep-apnoea.jpg",
    laserSleep:          "/assets/services/laser-sleep.jpg",
    dentalImplants:      "/assets/services/dental-implants.jpg",
    dentalImplants2:     "/assets/services/dental-implants-2.jpg",
    implantReadMore:     "/assets/services/implant-read-more.jpg",
    implantCost:         "/assets/services/implant-cost.jpg",
    implantGeneral:      "/assets/services/implant-general.jpg",
    allOnFour:           "/assets/services/all-on-four.jpg",
    allTeethOn4:         "/assets/services/all-teeth-on-4.jpg",
    gumLift:             "/assets/services/gum-lift.jpg",
    gumLift2:            "/assets/services/gum-lift-2.jpg",
    gumSolutions:        "/assets/services/gum-solutions.jpg",
    laserGumDisease:     "/assets/services/laser-gum-disease.jpg",
    laserGumDisease2:    "/assets/services/laser-gum-disease-2.jpg",
    gumDiseaseTreatment: "/assets/services/gum-disease-treatment.jpg",
    gumDiseaseSydney:    "/assets/services/gum-disease-sydney.jpg",
    snoring:             "/assets/services/snoring.jpg",
    snoring2:            "/assets/services/snoring-2.jpg",
    emergencyDentistry:  "/assets/services/emergency-dentistry.jpg",
    emergencyDentistry2: "/assets/services/emergency-dentistry-2.jpg",
    emergencyDentist:    "/assets/services/emergency-dentist.jpg",
    laserRootCanal:      "/assets/services/laser-root-canal.jpg",
    laserRootCanal2:     "/assets/services/laser-root-canal-2.jpg",
    grafting:            "/assets/services/grafting.jpg",
    grafting2:           "/assets/services/grafting-2.jpg",
    wisdomTeeth:         "/assets/services/wisdom-teeth.jpg",
    wisdomTeeth2:        "/assets/services/wisdom-teeth-2.jpg",
    tmjPain:             "/assets/services/tmj-pain.jpg",
    tmjPain2:            "/assets/services/tmj-pain-2.jpg",
    orthodonticsBraces:  "/assets/services/orthodontics-braces.jpg",
    braces:              "/assets/services/braces.jpg",
    lingualBraces:       "/assets/services/lingual-braces.jpg",
    aligners:            "/assets/services/aligners.jpg",
    functionalAppliances: "/assets/services/functional-appliances.jpg",
    paymentPlans:        "/assets/services/payment-plans.jpg",
    cosmeticProblems:    "/assets/services/cosmetic-problems.jpg",
    missingTeeth:        "/assets/services/missing-teeth.jpg",
    teethMissing:        "/assets/services/teeth-missing.jpg",
    oldFillings:         "/assets/services/old-fillings.jpg",
    generalDentistry:    "/assets/services/general-dentistry.jpg",
  },

  team: {
    drKinnarShah:  "/assets/team/dr-kinnar-shah.jpg",
    drManishShah:  "/assets/team/dr-manish-shah.jpg",
  },

  practice: {
    p1: "/assets/our-practice/P1.png",
    p2: "/assets/our-practice/P2.png",
    p3: "/assets/our-practice/P3.png",
    p4: "/assets/our-practice/P4.png",
    p5: "/assets/our-practice/P5.png",
    p6: "/assets/our-practice/P6.png",
  },

  misc: {
    pointScanBone: "/assets/visual-journey/point-scan-bone.jpg",
    pinkDrops:     "/assets/misc/pink-drops.jpg",
  },

  brand: {
    logo: "/assets/brand/cropped-logo_large-1.png",
    logoWhite: "/assets/brand/logo-white.png",
    favicon32: "/assets/brand/cropped-favicon-32x32.png",
    favicon192: "/assets/brand/cropped-favicon-192x192.png",
    affiliations: [
      { name: "ADA", src: "/assets/affiliations/ADA-logo.png" },
      { name: "ICOI", src: "/assets/affiliations/ICOI-logo.png" },
      { name: "ISCD", src: "/assets/affiliations/ISCD-logo.png" },
      { name: "International Association of Orthodontics", src: "/assets/affiliations/International-Association-of-Orthodontics-logo.png" },
      { name: "Australian Sleep Association", src: "/assets/affiliations/Australian-Sleep-Association-logo.png" },
      { name: "Australian Medical Association", src: "/assets/affiliations/Australian-Medical-Association-logo.png" },
      { name: "ASID", src: "/assets/affiliations/ASID-logo.png" },
      { name: "American Academy of Craniofacial Pain", src: "/assets/affiliations/American-Academy-of-Craniofacial-Pain-logo.png" },
      { name: "AACD", src: "/assets/affiliations/AACD-logo.png" },
      { name: "AADSM", src: "/assets/affiliations/AADSM-logo.png" },
      { name: "ACSDD", src: "/assets/affiliations/ACSDD-logo.png" },
    ],
  },
} as const;

// Helper type for type-safe image access
export type ImageCategory = keyof typeof images;
